### ISSUE TITLE
Bugfix: Double booking issue

### ISSUE THREAD

**Issue by eman0669** [shahril2206/AH_Artistry#2]
Need to resolve the bug where users and administrators can do double booking on the same time slot and date.
For references:
![WhatsApp Image 2024-12-29 at 22 28 29_3b638509](https://github.com/user-attachments/assets/503945a7-fe46-4cbe-8ba9-68c6f4e42ef7)
![WhatsApp Image 2024-12-29 at 22 28 29_32638fa0](https://github.com/user-attachments/assets/9e0234fb-05c8-400b-a4e3-9cc22cb65824)

**Comment by shahril2206** [comment]
Fixed by @eman0669 https://github.com/shahril2206/AH_Artistry/pull/1

Issue Closed
