### ISSUE TITLE
Bugfix: Double booking issue

### ISSUE THREAD

**Issue by eman0669** [shahril2206/AH_Artistry#3]
Need to resolve the bug where users and administrators can do double booking on the same time slot and date.
For references:
![WhatsApp Image 2024-12-29 at 22 28 29_e0346114](https://github.com/user-attachments/assets/d64fda57-bf37-4f01-876b-fbedf402349e)
![WhatsApp Image 2024-12-29 at 22 28 29_030af951](https://github.com/user-attachments/assets/095f6f60-ac27-497c-91f1-b4301fb75ab3)

**Comment by shahril2206** [comment]
#4 fixed by @eman0669 

Issue closed
