### ISSUE TITLE
Feature: New booking details page

### ISSUE THREAD

**Issue by eman0669** [shahril2206/AH_Artistry#7]
Admin requested to be able to see all the booking details where they can approve and reject through the website.
Proposed solution:
Add a new booking details page at the highlighted red box
![WhatsApp Image 2024-12-30 at 18 29 18_e5ae9d08](https://github.com/user-attachments/assets/60a1f6a8-976a-42ce-a118-c034638bef4f)

**Comment by shahril2206** [comment]
Admin booking details page

Proceed development

**Comment by shahril2206** [comment]
Fixed #8 by @eman0669 

Issue closed
